name: Big Data Workflow

on:
  push:
    branches:
      - main   # Se ejecuta en cambios en la rama principal
  workflow_dispatch:  # Permite activar el workflow manualmente desde GitHub

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"  # Cambia si necesitas otra versión de Python

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Paso 4: Ejecutar el script de generación de datos
    - name: Run data generation script
      run: python scripts/generar_datos.py

    # Paso 5: Ejecutar el script de limpieza de datos
    - name
